
try {
  runExample();  
} catch(err){
  trace(err);
}


